_wandb:
    value:
        cli_version: 0.23.0
        e:
            02fkeakp77bsskm2nofjz7earx93mi9t:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "5368709120"
                codePath: src/experiment.py
                codePathLocal: src/experiment.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "156622999552"
                email: carloalfieri03@gmail.com
                executable: /Users/carloalbertoalfieri/Desktop/FDS_PROJECT/.venv/bin/python3
                git:
                    commit: ae89981320e109f6de28ddd0fa9f0308e4fba098
                    remote: https://github.com/Catairu/FDS_PROJECT.git
                host: MacBook-Air-di-Carlo.local
                memory:
                    total: "8589934592"
                os: macOS-14.6.1-arm64-arm-64bit
                program: /Users/carloalbertoalfieri/Desktop/FDS_PROJECT/src/experiment.py
                python: CPython 3.12.11
                root: .
                startedAt: "2025-12-02T22:48:03.870218Z"
                writerId: 02fkeakp77bsskm2nofjz7earx93mi9t
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 41
                - 50
                - 106
            "2":
                - 1
                - 41
                - 50
                - 106
            "3":
                - 7
                - 13
                - 66
            "4": 3.12.11
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
cfg:
    value: '{''num_classes'': 6, ''block'': {''_target_'': ''net.cnn.ConvBlock'', ''in_channels'': ''${net.width}'', ''out_channels'': ''${net.width}'', ''kernel_size'': 3, ''pool_size'': 2}, ''embed'': {''_target_'': ''net.cnn.EncoderWrapper'', ''in_channels'': 9, ''layer_widths'': [64, 64, 64], ''kernel_size'': 3, ''stride'': 2}, ''unembed'': {''_target_'': ''torch.nn.LazyLinear'', ''out_features'': 6}, ''optimizer'': {''_target_'': ''torch.optim.Adam'', ''lr'': 0.001, ''weight_decay'': 0.0}, ''rnn_block'': {''_target_'': ''net.rnn.LSTMBlock'', ''input_size'': ''${net.width}'', ''hidden_size'': 128, ''num_layers'': 2, ''dropout'': 0.1, ''bidirectional'': False}, ''decoder'': {''_target_'': ''net.cnn.DecoderWrapper'', ''in_channels'': 64, ''layer_widths'': [64, 64, 9], ''kernel_size'': 3, ''stride'': 2, ''output_padding'': 1, ''use_batchnorm'': True}}'
